feat: Jenkins Agent
PsycleResearch/jenkins-agent-node-python pull request #1
Opened 2023-01-18 08:49 UTC by mbaumanndev

2023-01-18 08:59 UTC, danousna approved these changes

2023-01-18 09:20 UTC, Mindstan requested changes

2023-01-18 09:20 UTC, Mindstan commented on Dockerfile
> +RUN curl -sL https://deb.nodesource.com/setup_$NODE_VERSION.x -o nodesource_setup.sh
Ce serait mieux de tout mettre en un seul `RUN` (sinon les `rm` n’ont aucun effet si ce n’est de masquer le fichier).

2023-01-18 09:20 UTC, Mindstan commented on Dockerfile
> +RUN apt-get install nodejs
Attention tu oublies :
- de faire un `apt-get update`
- de mettre le _flag_ `-y` à `apt-get install` pour confirmer automatiquement l’installation
- de vider le cache APT (cf ligne 16 et 17)

2023-01-18 09:20 UTC, Mindstan commented on Dockerfile
> +    pip install opencv-python scipy==1.9.1 Cython --no-cache-dir
Je ne sais pas à quel point c’est utile de pré-installer ces paquets Python.

2023-01-18 10:00 UTC, mbaumanndev commented on Dockerfile
> +    pip install opencv-python scipy==1.9.1 Cython --no-cache-dir
J'ai l'impression qu'on s'en sert aussi bien sur IC que IV ou même certains scripts qu'on lance, si c'est vraiment pas crucial de le faire à cette étape je peux les retirés, le but c'est surtout de gagner un peu de temps en CI

2023-01-18 10:01 UTC, mbaumanndev commented on Dockerfile
> +RUN apt-get install nodejs
Le `apt-get update` doit être fait par `nodesource_setup.sh` car c'est comme ça qu'ils procèdent dans leur doc

2023-01-18 11:10 UTC, Mindstan commented on Dockerfile
> +RUN apt-get install nodejs
Si le script fait `add-apt-repository` c’est effectivement le cas, mais s’il écrit juste le fichier `list`, il faut le faire manuellement.

2023-01-18 11:11 UTC, Mindstan approved these changes

2023-01-18 11:11 UTC, Mindstan commented on Dockerfile
> +RUN pip install -U pip
j’ajouterais quand même `wheel` et `setuptools`.

2023-01-19 09:21 UTC, Mindstan approved these changes

2023-01-20 10:00 UTC, Mindstan requested changes

2023-01-25 09:08 UTC, Mindstan approved these changes

2023-01-25 09:20 UTC, merged